version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nest-app-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
      - '5555:5555'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev --poll=1000
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data_dev:
