# Usa una imagen de Node.js estable como base
FROM node:lts as builder

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos necesarios para instalar las dependencias
COPY package.json yarn.lock ./

# Instala solo las dependencias necesarias para construir
RUN yarn install --frozen-lockfile

# Copia todo el código fuente al contenedor
COPY . .

# Construye la aplicación
RUN yarn build

# Reduce el tamaño de la imagen final eliminando dependencias dev
RUN yarn install --production --frozen-lockfile

# Segunda etapa: imagen para producción
FROM node:lts-slim

# Define el directorio de trabajo
WORKDIR /app

# Copia los archivos de la etapa de construcción
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./

# Expone el puerto 3000
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["yarn", "start:prod"]
