version: '3.8'

networks:
  app_network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nest-app-prod
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: npm run start:prod
    networks:
      - app_network

  postgres:
    image: postgres:15
    container_name: postgres-dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data_prod:
